version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bookcatalog
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: qwerty
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  pgdata: